image: adoptopenjdk/openjdk8

stages:
  - lint
  - phpstan
  - notify

check_lint:
  stage: lint
  interruptible: true
  script:
    - java -version
    - uname -a
    - apt-get update -y
    - apt-get install make git -y
    - git config --global user.email "duke@mail.com"
    - git config --global user.name "Duke Javberg"
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$id_rsa" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - touch ~/.ssh/known_hosts
    - echo "$known_hosts" >> ~/.ssh/known_hosts
    - chmod 700 ~/.ssh
    - git clone git@git.tatmedia.com:tatmedia/ssl-checker-gui.git checker
    - cd checker
    - make update-config
    - make auto-create-jar
    - git status
    - git add .
    - git commit -m "received a new .jar"
    - git push -o ci.skip
